### ISSUE TITLE
Registration Endpoint Uri

### ISSUE THREAD

**Issue by rizamarhaban** [hadiidbouk/AppAuthIdentityServer4#2]
Hi, I have small question, what is Registration Endpoint Uri for and what are is the value related to:

registrationEndpointUri= "myRegistrationEndPointUri"

I cannot find in the properties from, e.g. myidserver/.well-known/openid-configuration

**Comment by hadiidbouk** [comment]
Hello,
In this sample , i haven't add the registration process yet , you can remove it or leave it blank.

Thank you

**Comment by hadiidbouk** [comment]
Close till I have another time to add this part
