### ISSUE TITLE
ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by Fatur** [hadiidbouk/AppAuthIdentityServer4#3]
Hi Hadi,
I've been stuck on this for hours now. Could you figure out what kind of error is this:
--------------------------------------------------------------------------------------------------------------------
This site can’t be reached

The webpage at myredirecturi://callback?code=25f48f30e57fcaf1f453cb5388dafa8c97c1664b983f77dd08f6382b0bed625f&scope=openid%20offline_access&state=hiTcqER1OtMp8eG-9Vkabw&session_state=Xt6HjtMoT67xESYzedeJ_JQccACHu-HwmOqgfxrDEZ8.7eef5f5f3020ddd230b7b18ab6b10d18# might be temporarily down or it may have moved permanently to a new web address.
ERR_UNKNOWN_URL_SCHEME
---------------------------------------------------------------------------------------------------------------
I got it after redirect back from identity server.

Thanks

**Comment by hadiidbouk** [comment]
Hello Fatur , 
Please check if you have insert the same redirect uri on the identity server and the android app.

Also don't forget to put the manifestPlaceholder in your build.gradle.
```
defaultConfig {
      .....
        manifestPlaceholders = [
                'appAuthRedirectScheme': 'myRedirectUri'
        ]
    }
```

And If you are using RedirectUriReceiverActivity :

```
	<activity
	 android:name="net.openid.appauth.RedirectUriReceiverActivity">
	       <intent-filter>
			<action android:name="android.intent.action.VIEW"/>
			 <category android:name="android.intent.category.DEFAULT"/>
			 <category android:name="android.intent.category.BROWSABLE"/>
			 <data android:scheme="myRedirectUri"/>
                </intent-filter>
	</activity>
```

You may see this error also when you are trying to perform a token request using  `mAuthService.performTokenRequest`

run the debuger and make sure that the `AuthorizationException` is null.

If the exception is null and you have perform a token request , that's mean everything is right but you haven't exit the activity browser.

**Comment by hadiidbouk** [comment]
Since there is no other comments here, I will close this issue.
